### ISSUE TITLE
Mac用户求一份easyX.h

### ISSUE THREAD

**Issue by HuaYuXiao** [LaTristan/TIN-related#1]
官网只提供了Windows的版本，但是MacBook用户无法获取easyX.h源文件，谢谢！

**Comment by LaTristan** [comment]
easyX.h依赖Windows系统服务，若仅需可视化建议考虑其他库如opengl、Qt（那几乎不用看这个自娱自乐的代码了🤣）；
若不需要可视化，可以做成管线交给下一步。
没有使用MacOS做过开发，用的stm32f407和jetpack Ubuntu，不好意思🫡

**Comment by HuaYuXiao** [comment]
> easyX.h依赖Windows系统服务，若仅需可视化建议考虑其他库如opengl、Qt（那几乎不用看这个自娱自乐的代码了🤣）； 若不需要可视化，可以做成管线交给下一步。 没有使用MacOS做过开发，用的stm32f407和jetpack Ubuntu，不好意思🫡

谢谢大佬！我打算放弃这个库了，先用opencv做一下可视化🙂
